"""empty message

Revision ID: 72c85e7c235b
Revises: 
Create Date: 2020-06-27 15:24:56.002463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72c85e7c235b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('ssnid', sa.Integer(), nullable=True),
    sa.Column('pname', sa.String(length=60), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('state', sa.String(length=60), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=False),
    sa.Column('bedtype', sa.String(length=15), nullable=False),
    sa.Column('pstatus', sa.String(length=10), nullable=False),
    sa.Column('admitdate', sa.Date(), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_on', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_index(op.f('ix_patients_ssnid'), 'patients', ['ssnid'], unique=True)
    op.create_table('userstore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=15), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), nullable=True),
    sa.Column('logged_in', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userstore')
    op.drop_index(op.f('ix_patients_ssnid'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
